### ISSUE TITLE
タスクまとめ

### ISSUE THREAD

**Issue by yustoris** [yustoris/cuneiform-detection#1]
# pre task
- [x] 対象となる文字のクラスを決める (almost done),頻度は取れてる -> 山内

# tasks
1. 行単位のdetection
    - [ ] 行単位の抽出 (almost done, つながってるところを断ち切る) -> 山内
2. 文字単位のdetectionを素直にやる
    - [ ] Neo-Assyrianのアノテーションデータを使う -> 細田さん
      - 対象文字クラスが決まってから
      - [ ] ヒッタイト語の対象となる文字のクラスのみを使う
    - [ ] 「サッカーボール作戦」 -> 細田さん
      - [ ] コーパスの各文字に対応して、粘土板の疑似教師データを作る
        - どうやってつくるのか？ and どのくらいつくるのか？
        - [x] コーパスのfetch -> 山内
        - [x] 文字別画像の取得 -> "note", "reading", "image", "sign": { "mszl_number", "sign_name", "abz_number" }
        - [ ] 取ってきた画像の中にどのくらいヒッタイト語の対象文字クラスにないものがあるか
           - [x] meszl_numberでジョイン (データセットi. と ii.) -> 細田さん
           - [x] 字体がヒッタイト語とどのくらい違うものがあるか -> 山内、細田さん
               - [x] データセットi. and iii.にある文字種
               - [x] データセットi. and ii.にある文字種
                  - [x] i. - ii. の文字種も出す
           - [ ] ヒッタイト語に足りない文字の画像をいくつか集める -> 山内
        - [ ] 透明背景同士を重ねてaugmentationできるかどうかの調査 -> 細田さん
        - [x] 背景の粘土板をどう処理するか
            - まずは2種類(白い・赤茶色)の背景を敷き詰める
      - [ ] データ生成スクリプトの実装
          - 行ごと
          - 斜めが再現されてるものもほしい
          - 白黒で出力
          - 背景と文字画像の境界をなじませることができるか？
          - 後は気持ちで
      - [ ] 学習コードの実装
    - [ ] 実際のヒッタイト語の粘土板のアノテーションを一部行う -> 山内
      - 5,000文字
3. Line and Sign level annotation
   - 1.でいいなら必要？
   - transliterationのデータを流用して水増しができるというメリットは有る
   - 余裕があったらでいいかな…

- 対象とならないマイナーな文字はどうするか？
  - 背景クラスとして扱う？
  - 無視する

**Comment by yustoris** [comment]
- 扱うデータセット
   1.  ヒッタイト語(マインツ大学)のテストセット (https://www.hethport.uni-wuerzburg.de/)
       - テキスト
       - 画像 (アノテーションなし)
   2. 文字画像ごとのデータセット (https://labasi.acdh.oeaw.ac.at/)
      -  時代がヒッタイトと違うので、字形が異なる場合がある -> ヒッタイトと同じものだけ使う
   3. アノテーション付きのデータセット (https://github.com/CompVis/cuneiform-sign-detection-dataset/tree/master/annotations)
      - 時代がヒッタイトと違うので、字形が異なる場合がある -> ヒッタイトと同じものだけ使う
